### ISSUE TITLE
bad file checksum

### ISSUE THREAD

**Issue by mholt** [nwaples/rardecode#10]
Hey, thanks for making this! I'm trying out this library with a rar file I had lying around; it contains zip files, and on one of them when I try to write the contents to a file, this error is returned:

> rardecode: bad file checksum

But other zip files contained in the archive previous to this one are read just fine. Does this mean the file is corrupted? I can send it to you privately if you'd like (just give me an email address to send the link to).

By the way, if this works out, I hope to add this to my [archiver](https://github.com/mholt/archiver) tool.

**Comment by nwaples** [comment]
Test it with unrar first. If that has no problems then you can send it to me (same username as github @gmail.com).

**Comment by mholt** [comment]
Thanks for your quick response! Indeed, unrar works on this archive without error. I'll send you my code and the link to the file to test it on. It could be that I'm just missing something simple in my code too.

**Comment by nwaples** [comment]
The problem file was encoded with an audio filter within rar. The VM must have a bug somewhere so it wasn't executing the audio filter bytecode correctly. I added a native implementation of the audio filter which works for me now. Ill have to look at fixing the VM later.

**Comment by mholt** [comment]
2b6967612a1476c34d857fba97e30db9bb1024cb appears to fix it! And d12226d24fe5392ff8741171d645417eea6ab3cc is an excellent feature too, thank you!
