### ISSUE TITLE
support for unpackver=20?

### ISSUE THREAD

**Issue by campbellr** [nwaples/rardecode#18]
I have a bunch of rar files that are (apparently) RAR4. Most of them fail to extract with `rardecode` with a `unsupported decoder version`. Adding some print statements shows that `unpackver` is `20`.

Is there any particular reason that it is unsupported (other than lack of time, say)?

Is expanding the set of supported versions/formats something that is in the pipeline?

If there are no huge blockers, I may take a stab at adding support (although at this point i know nothing about the rar format(s) except the little i've gleaned from scanning through this codebase and the c++ unrar codebase)

**Comment by nwaples** [comment]
I just had no files to test with. Current winrar, etc won't create the old versions.

I could have a go at it. I had a quick look, and since its the predecessor to 29 I could reuse/copy a bunch of stuff from it. It looks quite familiar. I might have to rework a few small things, as I couldn't see any explicit end of block marker in the format.

Having a test file would make it easier.

**Comment by campbellr** [comment]
That would be great. I can upload the rar file that was failing somewhere and attach a link here if you want.

**Comment by nwaples** [comment]
Sure, that would be good.

**Comment by nwaples** [comment]
I've added some code in the experimental branch for unpackver 20. Its untested, but if you are very lucky maybe it will work.

**Comment by davidnewhall** [comment]
No idea what version these files are, but this library will not extract them. Found them in some 10+ year old torrents. Hoping you can make it work! 🤞 I put both RAR files inside a zip file so GitHub would accept them. 
- `b2b_gui01b.rar` produces `rardecode: unsupported decoder version`
- `dc_selfboot_kit.rar` produces `rardecode: bad header crc`

[Archive.zip](https://github.com/nwaples/rardecode/files/10200982/Archive.zip)

**Comment by nwaples** [comment]
This should be fixed now, sorry for the delay
