### ISSUE TITLE
panic: time: missing Location in call to Date, archive15.go#L132

### ISSUE THREAD

**Issue by davidnewhall** [nwaples/rardecode#25]
Hello!

I just had a user open an issue for a crash I've never seen before.  This is after ~2 years of use and tens of thousands of users.

You can see the stack trace here https://github.com/davidnewhall/unpackerr/issues/142
The stack ends here: https://github.com/nwaples/rardecode/blob/master/archive15.go#L132
`panic: time: missing Location in call to Date`

I'm not real sure where to begin with this, and was hoping you could give me some guidance. Do you think this is specific to the archive? I'm assuming it must be. Or perhaps specific to the user's system? He mentioned it's happened several times, which is several times more than anyone else has seen this. Maybe it has something to do with a time zone? I can't say I've ever actually used `time.Date()` anywhere..

Appreciate any thoughts you may have. Thanks!

**Comment by davidnewhall** [comment]
It probably has something to do with this: https://github.com/davidnewhall/unpackerr/blob/master/main.go#L38-L40

Asked the user for startup logs, where this error would appear.

**Comment by davidnewhall** [comment]
And shoot, while I'm here, this might be a bug in the rardecode library too: https://github.com/davidnewhall/unpackerr/issues/140

If you have any thoughts on that, I'd love to hear 'em!

**Comment by nwaples** [comment]
> It probably has something to do with this: https://github.com/davidnewhall/unpackerr/blob/master/main.go#L38-L40
> 
> Asked the user for startup logs, where this error would appear.

 That would cause the panic.  time.Local is being set to nil when when LoadLocation fails and time.Date panics

https://cs.opensource.google/go/go/+/refs/tags/go1.16.6:src/time/time.go;l=1342-1345

So, don't set time.Local if it fails. Though Im not sure of the need to change time.Local. The go standard library already sets it based on the TZ env (for unix systems at least). 
https://pkg.go.dev/time#Location

**Comment by davidnewhall** [comment]
Yeah, this is definitely my hunch. I'm going to refactor that code to avoid this. Thanks for your response! Still curious about that [other one](https://github.com/davidnewhall/unpackerr/issues/140). I looked around in archive.go and archive15.go. It seems to be detecting the archive naming scheme incorrectly.

**Comment by nwaples** [comment]
It probably an issue with the naming system. In archive.go nextVolumeName() I try to replicate how unrar does it in https://github.com/pmachapman/unrar/blob/master/pathfn.cpp#L356 .

There are 2 naming schemes for rar archives. Old and new. Old is the .rar, .r00, .r01, etc. New is .part1.rar, .part2.rar, or even .part1of3.rar, .part2of3.rar, etc.  Newer versions of rar archives are supposed to use only the new format. Some older versions can do either (there is a bit in the archive that says if it is new or old naming scheme).

I default to using the new scheme, and use the old scheme if the archive has that flag set to use the old, or it can't find any digits in the filename. There is the chance that the files were renamed, but I can't be certain without looking at the files. One thing I could do is refactor the code to fallback to trying the old style if the opeing the new style next filename fails.

**Comment by davidnewhall** [comment]
I had to deal with this a bit, but probably didn't get as detailed as you did. My code is here https://github.com/golift/xtractr/blob/master/files.go#L98-L126

I'm not sure if that's helpful, but it looks like I just check for a file with the suffix `.r00` to determine if it's the old style or not.

**Comment by davidnewhall** [comment]
Closing this since the original issue is my problem (and now fixed). Thanks!
