### ISSUE TITLE
Rar naming convention not properly detected when filenames have numbers

### ISSUE THREAD

**Issue by davidnewhall** [nwaples/rardecode#26]
Hello, a user of mine opened an issue about a rar archive not being properly extracted. We discussed this briefly on #25. I'm just making a new issue to keep these separate. This replaces and closes #25.

Original report with details of the"bug" can be found here: davidnewhall/unpackerr#140

**Comment by nwaples** [comment]
Ive created a new version which falls back to old style naming if new style fails to open. Hopefully that will fix it.

**Comment by davidnewhall** [comment]
Thanks! I'll put together a new release of my app and we shall see! I'm hampered by Docker shutting off my builds, so it may be a bit before I can get around to making everything work (so I can cut a new release). Really appreciate you getting to this so quickly!

**Comment by davidnewhall** [comment]
I have had no reports of issues, so I'm going to close this out. Thanks for the quick fix!
