### ISSUE TITLE
panic in decodeSymbol2

### ISSUE THREAD

**Issue by secDre4mer** [nwaples/rardecode#27]
When unpacking `Cscan(.net_2x_3x).exe` from https://github.com/k8gege/K8tools/blob/master/K8Cscan5.4_20191101.rar, rardecode panics in decodeSymbol2, line 805:

`for m.charMask[states[i].sym] == m.escCount {`

Apparently `i` equals `len(states)` (both 22), causing the issue.

If there is any further information that you require, please let me know.

**Comment by nwaples** [comment]
If I use the experimental branch, It no longer panic's but it still has corrupt ppm data errors. Are the archive files not valid/corrupt?

**Comment by secDre4mer** [comment]
Possibly - I haven't created them and don't know. They're encrypted, might that cause the errors?

**Comment by nwaples** [comment]
Yes, that would happen if they are encrypted.

I copied the development version of ppm_model.go to main branch and tagged a new version. It seem to at least not panic for that file.
