### ISSUE TITLE
support RAR7

### ISSUE THREAD

**Issue by wallcwr** [nwaples/rardecode#38]
When I parse the file generated by rar7, the following error is reported: "rardecode: unknown decoder version"
, Can you support rar7

**Comment by nwaples** [comment]
I will have to look. Nothing soon, its probably a reasonable effort to do so.

**Comment by nwaples** [comment]
Ive added some code for rar7.
If that doesnt work, send the output of 
 rar lt <rarfile>

**Comment by wallcwr** [comment]
thank you very much
