### ISSUE TITLE
Unable to get modtime/date from rar file

### ISSUE THREAD

**Issue by mholt** [nwaples/rardecode#39]
One of my package's users has [reported](https://github.com/mholt/archiver/issues/420) that they can't get the dates from the contents of their rar file (linked in one of the later comments). I was able to confirm this, by printing the header values we get while iterating the entries:

> &{ ... IsDir:false Solid:false HostOS:3 Attributes:32 PackedSize:7837 UnPackedSize:8090 UnKnownSize:false ModificationTime:0001-01-01 00:00:00 +0000 UTC CreationTime:0001-01-01 00:00:00 +0000 UTC AccessTime:0001-01-01 00:00:00 +0000 UTC Version:0}

But when I open the rar file using the Gnome archive utility it shows mod times just fine. Any ideas? :thinking:

**Comment by nwaples** [comment]
Nothing immediately. I will have to debug it

**Comment by nwaples** [comment]
I never implemented the code for v5 optional precision file times.
I added a commit which hopefully fixes it.

**Comment by mholt** [comment]
Awesome, that works now!! Thank you very much :smiley:
