### ISSUE TITLE
Error reading encrypted rar archives

### ISSUE THREAD

**Issue by SleuthKid** [nwaples/rardecode#4]
The library throws a runtime panic when trying to read an encrypted RAR archive with providing an empty password. Sorry - but I can not provide a stacktrace.

To create a file that reproduces the error:
<code>rar a -p test_enc.rar some_file.txt</code>

I used rardecode.NewReader(r, "") as starting point. It seems to crash in the huffman decoder at rar.Next() (-> rardecode.readCodeLengthTable)

**Comment by nwaples** [comment]
Sorry, fixed it (I hope). It should now produce an error.

I should probably change the errors to just be "Corrupt Data or Bad Password" instead of the more specific messages like "corrupt ppm data", "huffman decode failed" that are probably more confusing than useful.

**Comment by SleuthKid** [comment]
Thank you for the quick reply. I can confirm this fixes the panic for my test cases and returns a proper error that can be used to skip the file.

I agree on the idea of speaking error messages.

**Comment by SleuthKid** [comment]
All errors have been properly addressed in the latest commits.
