### ISSUE TITLE
Determine whether RAR4 file is encrypted

### ISSUE THREAD

**Issue by wallcwr** [nwaples/rardecode#40]
When I use WinRAR to encrypt a file in Windows, I use the following code on Linux to determine whether the file is encrypted. The result returned is that the file is not encrypted. In fact, the file is encrypted.

```go
func isEncrypted(path string) (encrypted bool, err error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()
	
	rr, err := rardecode.OpenReader(path)
	if err != nil {
		return false, err
	}
	
	buf := make([]byte, 1024*1024)
	for {
		_, err = rr.Read(buf)
		if err != nil {
			if strings.Contains(err.Error(), "incorrect password") {
				return true, nil
			}
			if strings.Contains(err.Error(), "EOF") {
				break
			}
			return false, err
		}
	}

	return false, nil
}

```

**Comment by nwaples** [comment]
I will have to change the code to give an error if it comes across encryption if there was no password supplied. Currently it assumes a default empty password and tries that.

**Comment by nwaples** [comment]
The latest commits add a Encrypted field to the FileHeader. 
There is also two new errors, ErrArchiveEncrypted and ErrArchivedFileEncrypted that can occur if you read an encrypted archive without supplying a password. The first is if the archive headers are encrypted, and in this case you can't even list the files in the archive. The second is for when only the file contents are encrypted, so you cycle through all files (or List) and you will only get that error when trying to read the file contents.
